training:
  output_dir: "./gpt2-curriculum"
  num_train_epochs: 3
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 4
  save_steps: 10000
  save_total_limit: 2
  logging_steps: 100
  eval_steps: 500
